---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-frontend-staging
spec:
  acme:
    email: <YOUR_EMAIL_ADDRESS>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-frontend-staging-private-key
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx
